version: '2'
services:
  roscore:
    image: 141.69.58.19:5000/iki/marvin:kinetic
    environment:
      WAIT_FOR_ROSCORE: 0
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
    stdin_open: true
    network_mode: host
    restart: "unless-stopped"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - $HOME/catkin_ws:/root/catkin_ws
    tty: true
    command:
    - roscore
    labels:
      io.rancher.container.pull_image: never
      io.rancher.scheduler.affinity:host_label: hostname=marvin
